[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
exclude = (?x)(
    f469-disco/
    | bootloader/
    | \.bundle\.tar/
    | build/
    )

[mypy-ucryptolib.*]
ignore_missing_imports = True

[mypy-ubinascii.*]
ignore_missing_imports = True

[mypy-uhashlib.*]
ignore_missing_imports = True

[mypy-pyb.*]
ignore_missing_imports = True

[mypy-machine.*]
ignore_missing_imports = True

[mypy-embit.*]
ignore_missing_imports = True
